### ISSUE TITLE
Migrate from Heroku

### ISSUE THREAD

**Issue by sue445** [sue445/cure-mastodon-bots#799]
c.f. https://blog.heroku.com/next-chapter

# TODO
* [x] Remove sinatra app
* [x] Don't deploy to Heroku
* [x] Run bot on CI
* [x] Stop Heroku Scheduler
